---
id: webmail
name: Horde Groupware Webmail Edition
full: Horde Groupware Webmail Edition
description: >-
  Horde Groupware Webmail Edition is a free, enterprise ready, browser based
  communication suite. Users can read, send and organize email messages with
  three different webmail interfaces and manage and share calendars, contacts,
  tasks and notes with the standards compliant components from the Horde
  Project.
list: horde
type: application
homepage: https://www.horde.org/apps/webmail
authors:
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
version:
  release: 5.2.23
  api: 5.2.0
state:
  release: stable
  api: stable
license:
  identifier: OSI certified
  uri: http://www.horde.org/licenses/
dependencies:
  required:
    php: ^5.3 || ^7
    pear:
      pear.horde.org/groupware:
        version: '*'
        conflicts: true
      pear.horde.org/content: ^2.0.6
      pear.horde.org/gollem: ^3.0.12
      pear.horde.org/horde: ^5.2.17
      pear.horde.org/imp: ^6.2.21
      pear.horde.org/ingo: ^3.2.16
      pear.horde.org/kronolith: ^4.2.23
      pear.horde.org/mnemo: ^4.2.14
      pear.horde.org/nag: ^4.2.17
      pear.horde.org/timeobjects: ^2.1.4
      pear.horde.org/trean: ^1.1.9
      pear.horde.org/turba: ^4.2.21
